version: "3.11"
services:
  chatbot:
    build: .
    ports:
      - "8000:8000"
    deploy:
      resources:
        reservations:
          devices:
              - driver: nvidia
                count: all
                capabilities: [ gpu ]
    restart: unless-stopped
